name: This is simple action file for Go

on: 
  push:
    branches: [ main ]
    paths:
      - 'src/Go/*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          go-version: [ '1.19', '1.20' ]

    steps:
      - uses: actions/checkout@v5
      - name: Set up the Go 
        uses: actions/setup-go@v5
        with: 
          go-version: ${{matrix.go-version}}

      - name: print the go go-version
        run: go version
